### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by iamabear09** [iamabear09/WIL#3]
`Grafana` 관련 경험 및 공부 기록

**Comment by iamabear09** [comment]
## [Provision Grafana](https://grafana.com/docs/grafana/latest/administration/provisioning/)

- provisioning system that uses config files.
- `data sources` and `dashboards` can be defined 
   - via **files** that can be version controlled.

<br><br>

## [prometheus-data-source](https://grafana.com/docs/grafana/latest/datasources/prometheus/#prometheus-data-source)

- [Example data source config file](https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file)


<br><br>

### [Using Environment Variables](https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables)

```
datasources:
  - name: Graphite
    url: http://localhost:$PORT
    user: $USER
    secureJsonData:
      password: $PASSWORD
```
